Repository sul-dlss/wallscreens, pull requests merged in 2021-11, with the labels that each got.

#129 Add missing image to Adobe and Apple slideshow
  _data/experiences/adobe-and-apple.yaml
Labels: slideshow

#130 Add local images to Adobe and Apple slideshow
  _data/experiences/adobe-and-apple.yaml
Labels: slideshow, physical

#131 Add local images to Bay Area Video Arcades
  _data/experiences/video-arcades.yaml
Labels: slideshow, physical

#134 Use full-sized local_image for Medical Devices
  _data/experiences/medical-devices.yaml
Labels: guided tour

#140 Update image order for oral history homescreen attractor
  _data/experiences/silicon-genesis.yaml
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-01.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-02.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-03.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-04.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-05.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-06.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-07.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-08.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-09.png
  images/wallscreens/silicon-valley/silicon-genesis/attract-images/silicon-genesis-10.png
Labels: oral history

#141 Use full-sized local image for Networking guided tour
  _data/experiences/networking.yaml
Labels: guided tour, physical

#161 Fix up Adobe and Apple local images
  _data/experiences/adobe-and-apple.yaml
Labels: slideshow

#159 Add slideshow 2 Ric Weiland to wallscreen 11.
  _data/experiences/richard-weiland.yaml
  _data/wallscreens/perspectives.yaml
  _wallscreens/perspectives/richard-weiland/index.html
Labels: slideshow

#165 Add experience subtitles to slideshow data and layouts
  _data/experiences/adobe-and-apple.yaml
  _data/experiences/labor.yaml
  _data/experiences/richard-weiland.yaml
  _data/experiences/video-arcades.yaml
  _includes/_dig_deeper.html
  _includes/_oral_history.html
  _includes/_slideshow.html
  _scss/wallscreens/_cards.scss
  _scss/wallscreens/experiences/_slideshow.scss
Labels: slideshow

#268 Update video file versions
  _data/experiences/medical-technology.yaml
  _data/experiences/silicon-genesis.yaml
Labels: oral history
